'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { Provider } from 'react-redux';
import Store from '../reducers/Store';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <Provider store={Store}>
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </Provider>
      </html>
    
  )
}
